{"name": "test_login[resume_list]", "status": "broken", "statusDetails": {"message": "KeyError: 'test'", "trace": "self = <test_01.Test_choice object at 0x000001BBB7841C08>, name = 'resume_list'\n\n    @allure.feature('测试用例1')\n    @pytest.mark.parametrize('name', (case.caae_name[\"choice\"][\"login\"]))\n    def test_login(self,name):\n>       self.pytestObject(self,name)\n\ntest_01.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\base\\PytestObject.py:14: in pytestObject\n    assertion=case.run(module,name)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <base.CaseOperate.Case object at 0x000001BBB75FAC88>, class_name = 'choice', name = 'resume_list'\n\n    def run(self, class_name, name):\n        request_list = self.request[class_name][name]\n>       url = request_list[\"url\"].format(data=test.data)\nE       KeyError: 'test'\n\n..\\base\\CaseOperate.py:59: KeyError"}, "parameters": [{"name": "name", "value": "'resume_list'"}], "start": 1605491458875, "stop": 1605491458875, "uuid": "bf8e0416-8554-414b-b2d4-0f2d6167c37c", "historyId": "fe2c57efd2814363f2cee5498638569e", "testCaseId": "29833af1bc62bae296571ec4b1662ac8", "fullName": "test_01.Test_choice#test_login", "labels": [{"name": "feature", "value": "测试用例1"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "Test_choice"}, {"name": "host", "value": "LAPTOP-4V3QBUP4"}, {"name": "thread", "value": "13576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}