{"name": "test_login[resume_list]", "status": "broken", "statusDetails": {"message": "KeyError: 'resume_list'", "trace": "self = <test_01.Test_choice object at 0x000001F894432B88>, name = 'resume_list'\n\n    @allure.feature('测试用例1')\n    @pytest.mark.parametrize('name', (case.caae_name[\"choice\"][\"login\"]))\n    def test_login(self,name):\n>       self.pytestObject(self,name)\n\ntest_01.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\base\\PytestObject.py:13: in pytestObject\n    assertion=case.run(module,name)\n..\\base\\CaseOperate.py:60: in run\n    body = self.myReplace(json.dumps(request_list['body']),name)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <base.CaseOperate.Case object at 0x000001F8941A99C8>, body = '{}', name = 'resume_list'\n\n    def myReplace(self, body,name):\n>       obj=MyObject.dict_to_object({name:test.data[name]})\nE       KeyError: 'resume_list'\n\n..\\base\\CaseOperate.py:32: KeyError"}, "parameters": [{"name": "name", "value": "'resume_list'"}], "start": 1605251180397, "stop": 1605251180397, "uuid": "fae43e24-5bda-458b-9a7c-5be8aaeee82e", "historyId": "fe2c57efd2814363f2cee5498638569e", "testCaseId": "29833af1bc62bae296571ec4b1662ac8", "fullName": "test_01.Test_choice#test_login", "labels": [{"name": "feature", "value": "测试用例1"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "Test_choice"}, {"name": "host", "value": "LAPTOP-4V3QBUP4"}, {"name": "thread", "value": "12228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}