{"status": "broken", "uuid": "0b03f325-7818-4c3c-b77c-0b753515d876", "labels": [{"name": "feature", "value": "getRegionHomeNumbers"}, {"name": "suite", "value": "test_sample"}, {"name": "host", "value": "LAPTOP-1DMUQ9HH"}, {"name": "thread", "value": "2360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "test_sample"}], "stop": 1590717203366, "testCaseId": "9beadc97dc745b04781917721fc2fee6", "historyId": "bcf5c0b3b21ee411ee5a11e7417fbe6b", "start": 1590717203366, "fullName": "test_sample#test_2", "statusDetails": {"message": "AttributeError: type object 'api_test' has no attribute 'uri'", "trace": "@allure.feature('getRegionHomeNumbers')\n    def test_2():\n>       success=test01.getregion()\n\ntest_sample.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <case.monitoring.monitoring object at 0x00000000047243C8>\n\n    def getregion(self):\n        name = \"getRegionHomeNumbers\"\n        url = '/getRegionHomeNumbers?area='\n>       headers = {\"Accept\": \"application/json, text/plain, */*\",  \"Origin\": test.uri, \"Referer\": test.uri}\nE       AttributeError: type object 'api_test' has no attribute 'uri'\n\n..\\case\\monitoring.py:17: AttributeError"}, "name": "test_2"}